version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: on-failure
    ports:
      - "3306:3306"
    networks:
      b2p-bridge:
        ipv4_address: ${DOCKER_DB_IP_ADDRESS}
    volumes:
      - wpdb:/var/lib/mysql
      - $HOME/DDK/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: ${DB_PASSWORD}
  dbtests:
    image: mysql:5.7
    restart: on-failure
    ports:
      - "3308:3306"
    networks:
      b2p-bridge:
        ipv4_address: ${DOCKER_DB_TESTS_IP_ADDRESS}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_TESTS_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wptests
      MYSQL_PASSWORD: ${DB_TESTS_PASSWORD}
  nginx:
    image: nginx
    restart: on-failure
    ports:
      - "80:80"
    networks:
      - b2p-bridge
    links:
      - wordpress:php-fpm-server
    depends_on:
      - wordpress
    volumes:
#      - ./wordpress:/var/www/html
      - wordpress-sync:/var/www/html:nocopy
      - plugin-sync:/var/www/html/wp-content/plugins/pull-comments-other-pages:nocopy
      - $HOME/DDK/nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
  wordpress:
    image: kumaxim/xdebug-wordpress:php7.4-fpm
    restart: on-failure
    links:
      - db:mysql
    depends_on:
      - db
    expose:
      - "9000"
      - "9900"
    networks:
      - b2p-bridge
    volumes:
      - wordpress-sync:/var/www/html:nocopy
#      - ./wordpress:/var/www/html
      - plugin-sync:/var/www/html/wp-content/plugins/pull-comments-other-pages:nocopy
      - $HOME/DDK/docker-php-core-settings.ini:/usr/local/etc/php/conf.d/docker-php-core-settings.ini:ro
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      XDEBUG_ENABLE: 1
#      XDEBUG_REMOTE_ENABLE: 1
#      XDEBUG_REMOTE_AUTOSTART: 1
#      XDEBUG_REMOTE_PORT: 9900
#      XDEBUG_IDEKEY: phpstorm
#      XDEBUG_REMOTE_HOST: "host.docker.internal"
      XDEBUG_REMOTE_HOST: "172.31.0.1"
  wpcli:
    image: wordpress:cli
    restart: on-failure
    networks:
      - b2p-bridge
    depends_on:
      - db
      - dbtests
      - wordpress
    command: ['tail', '-f', '/dev/null']
    volumes:
#      - ./wordpress:/var/www/html
      - wordpress-sync:/var/www/html:nocopy
      - plugin-sync:/var/www/html/wp-content/plugins/pull-comments-other-pages:nocopy
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WP_CLI_CONFIG_PATH: /var/www/html/wp-content/plugins/pull-comments-other-pages/wp-cli.yml

volumes:
  wpdb:
  wordpress-sync:
    external: true
  plugin-sync:
    external: true

networks:
  b2p-bridge:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_NETWORK_RANGE}