name: Build Plugin Release

on:
  push:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-plugin:
    runs-on: ubuntu-latest
#    container: wordpress:cli-2.6-php7.4

    services:
      nginx:
        image: nginx:latest
        ports:
          - 80:80

      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wpuser
          MYSQL_PASSWORD: ${{ secrets.MYSQL_DB_PASSWORD }}

      wordpress:
        image: wordpress:6.0-php7.4-fpm
        env:
          WORDPRESS_DB_HOST: mysql
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wpuser
          MYSQL_PASSWORD: ${{ secrets.MYSQL_DB_PASSWORD }}
        volumes:
          - wordpress:/var/www/html
#        depends_on:
#          - mysql

      wpcli:
        image: wordpress:cli-2.6-php7.4
        env:
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wpuser
          MYSQL_PASSWORD: ${{ secrets.MYSQL_DB_PASSWORD }}
        volumes:
          - wordpress:/var/www/html
        options: >-
          --name wpcli_service

#        depends_on:
#          - mysql
#          - wordpress

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Get WordPress version
          run: |
            docker run wpcli_service core version

      - name: Setup NodeJS v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Compile Assets
        run: |
          yarn install --frozen-lockfile --ignore-scripts
          yarn run lint:scripts
          yarn run lint:styles
          yarn run build:production

      - name: Cache Composer Dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer Dependencies
        uses: php-actions/composer@v6
        with:
          progress: 'yes'
          php_version: '7.4'
          command: update --optimize-autoloader

      - name: Composer Script - Lint PHP Files
        uses: php-actions/composer@v6
        with:
          php_version: '7.4'
          command: run-script lint:php

      - name: Composer Script - Build Archive
        uses: php-actions/composer@v6
        with:
          progress: 'yes'
          php_version: '7.4'
          command: run-script build:production

#  perform-e2e-tests:
#    needs: build-plugin
#    runs-on: ubuntu-latest
#    container:
#      image: mysql:5.7
#      env:
#        MYSQL_ROOT_PASSWORD: ${{ steps.dotenv.outputs.DB_ROOT_PASSWORD }}
#        MYSQL_DATABASE: wordpress
#        MYSQL_USER: wpuser
#        MYSQL_PASSWORD: ${{ steps.dotenv.outputs.DB_PASSWORD }}
#    steps:
#      - name: Check out repository code
#        uses: actions/checkout@v3
#
#      - name: Composer Script - Generate .env
#        uses: php-actions/composer@v6
#        with:
#          php_version: '7.4'
#          command: run-script env:generate
#
#      - name: Publish Enviroment from .env
#        id: dotenv
#        uses: falti/dotenv-action@v0.2
#        with:
#          log-variables: true
#
#      - name: Output .env
#        run: |
#            echo ${{ steps.dotenv.outputs.DB_ROOT_PASSWORD }}
#            echo ${{ steps.dotenv.outputs.DB_PASSWORD }}

#  publish-gh-release:
#    needs: perform-e2e-tests
#    runs-on: ubuntu-latest
#      steps:
#      - name: Publish Release
#        uses: softprops/action-gh-release@v1
#        with:
#          draft: true
#          file: 'pull-comments-other-pages.zip'

#  upload-in-plugin-directory:
#    needs: perform-e2e-tests
#    runs-on: ubuntu-latest
#      steps: