name: Build Plugin Release

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  create-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build Assets
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: |
          npm i --ignore-scripts
          npm rum lint:scripts
          npm run lint:styles
          npm run build:production
      - name: Install Composer Dependencies
        uses: php-actions/composer@v6
        with:
          progress: 'yes'
          php_version: '7.4'
      - name: Composer Script - Generate .env
        uses: php-actions/composer@v6
        with:
          command: run-script env:generate
      - name: Composer Script - Lint PHP Files
          uses: php-actions/composer@v6
          with:
            command: run-script lint:php
      - name: Composer Script - Build Archive
          uses: php-actions/composer@v6
          with:
            command: run-script build:production
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          file: 'pull-comments-other-pages.zip'

